[project]
name = "yandex-practicum"
version = "0.1.0"
description = "Yandex Practicum algo courses"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
    "ruff>=0.15.1",
]

[tool.ruff]
# Ограничение длины строки (например, 100 или 120 символов)
line-length = 100
target-version = "py313"

[tool.ruff.lint]
# Включаем полезные правила:
# E, W - стандартные ошибки pycodestyle
# F - Pyflakes
# I - isort (сортировка импортов)
# B - flake8-bugbear (полезные находки багов)
# UP - pyupgrade (автоматически обновляет синтаксис под новую версию Python)
select = ["E", "W", "F", "I", "B", "UP"]
ignore = []

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["sprint_1, sprint_2, sprint_3, sprint_4"]
python_files = "test_*.py *_test.py"
python_functions = "test_*"
addopts = [
  "-vv",				       
  "--import-mode=importlib"  	
]
